pipeline:

  test:
    image: node:alpine
    commands:
      - yarn install
      - yarn run test

  publish:
    image: plugins/docker
    repo: ethicaljobs/drone-gce-deploy
    when:
      event: tag
    secrets: [
        docker_username,
        docker_password
    ]
    tags: [
        'latest',
        '${DRONE_TAG=${DRONE_COMMIT}}'
    ]
