pipeline:
  dependancies:
    image: node:alpine
    commands:
      - yarn install

  test:
    image: node:alpine
    commands:
      - yarn run test

  publish:
    image: plugins/docker
    # environment:
    #   HOME: "/tmp"
    repo: ethicaljobs/drone-gce-deploy
    secrets: [ docker_username, docker_password ]
    tags:
      - latest
      - '${DRONE_TAG=${DRONE_COMMIT=latest}}'
    when:
      event: tag

  notify-slack:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: deployments
    when:
      status: changed
