pipeline:

  test:
    image: node:alpine
    commands:
      - yarn install
      - yarn run test

  publish:
    image: plugins/docker
    repo: ethicaljobs/drone-gce-deploy
    username: ${DOCKER_USERNAME}
    password: ${DOCKER_PASSWORD}
    tags:
      - latest
      - ${DRONE_TAG=${DRONE_COMMIT}}

