kind: pipeline
name: default
steps:

  - name: dependancies
    image: node:alpine
    commands:
      - yarn install

  - name: test
    image: node:alpine
    commands:
      - yarn run test

  - name: publish
    image: plugins/docker
    # environment:
    #   HOME: "/tmp"
    settings:
      repo: ethicaljobs/drone-gce-deploy
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      tags:
        - latest
        - '${DRONE_TAG=${DRONE_COMMIT=latest}}'
