apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    name: test-service
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: test-service
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 3
    spec:
      containers:
      - name: test-container-1
        imagePullPolicy: Always
        image: docker/repo:{{=template.drone.tag}}
        ports:
            - containerPort: 80
      - name: test-container-2
        imagePullPolicy: Always
        image: docker/repo:{{=template.environment.FOO || template.environment.BAR}}
        ports:
            - containerPort: 80
